name: Container timezone

on:
  push:
    paths:
      - ".github/workflows/container-timezone.yml"

env:
  TZ: Asia/Tokyo

jobs:
  set-timezone-in-container:
    runs-on: ubuntu-latest

    container:
      image: ubuntu:22.04

    steps:
      - name: Install tzdata
        run: |
          apt-get update
          apt-get install -y tzdata

      - name: Show datetime
        run: |
          date "+%Y/%m/%d %H:%M:%S"

      - name: Show datetime with TZ env from workflow
        run: |
          date "+%Y/%m/%d %H:%M:%S"
        env:
          TZ: Asia/Tokyo

      - name: Show datetime with TZ env from command line
        run: |
          TZ=Asia/Tokyo date "+%Y/%m/%d %H:%M:%S"
