name: test

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  test:
    runs-on: ubuntu-latest

    container:
      image: ubuntu:22.04
      env:
        TZ: Asia/Tokyo

    steps:
      - name: test
        run: |
          echo hello

      - name: test2
        run: |
          echo world
